---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
    run_list:
      - recipe[create::_centos]
  - name: centos-7.0
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[create::default]
